Create main.yml
Lepart23/Lepart23 pull request #1
Opened 2022-05-29 12:07 UTC by Lepart23

2023-03-16 15:36 UTC, merged

2023-05-06 14:16 UTC, Lepart23 commented on .github/workflows/main.yml
> +on:
[]()

2023-11-12 21:00 UTC, Lepart23 commented on .github/workflows/main.yml
> +on:
Bajka

2025-04-23 01:50 UTC, heo4200000 requested changes
#

2025-04-23 01:51 UTC, heo4200000 approved these changes